# Generated by Django 2.1 on 2018-08-16 03:54

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180813_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章正文'),
        ),
    ]
