# Generated by Django 2.1 on 2018-08-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180816_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='新闻标题')),
                ('url', models.CharField(max_length=300, verbose_name='新闻链接')),
            ],
        ),
    ]
