# Generated by Django 2.1 on 2018-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_time'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AddField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
