# Generated by Django 2.1 on 2018-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180817_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
